# Generated by Django 4.2.6 on 2023-10-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge_record',
            name='amount_left',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
