# Generated by Django 4.2.6 on 2023-10-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_recharge_record_amount_left_delete_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_card',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
