# Generated by Django 4.2.6 on 2023-10-12 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_bank_card_bank_name'),
        ('dashboard', '0003_rename_card_number_bank_card_account_number_and_more'),
    ]

    operations = [
    ]
