# Generated by Django 4.2.6 on 2023-10-17 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_merge_20231012_0558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='date',
            new_name='date_purchase',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
        migrations.RemoveField(
            model_name='recharge_record',
            name='amount_left',
        ),
    ]
