# Generated by Django 4.2.6 on 2023-10-18 08:18
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_merge_20231012_0558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='date',
            new_name='date_purchase',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
        migrations.RemoveField(
            model_name='recharge_record',
            name='amount_left',
        ),
        migrations.AddField(
            model_name='recharge_record',
            name='payment_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
