# Generated by Django 4.2.6 on 2023-10-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_date_orders_date_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge_record',
            name='payment_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
