# Generated by Django 4.2.6 on 2023-10-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_payment_id_recharge_record_recharge_payment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recharge_Record',
        ),
    ]
