# Generated by Django 4.2.6 on 2023-10-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_recharge_record_user_recharge_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge_record',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdraw_record',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
