# Generated by Django 4.2.6 on 2023-10-18 09:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_is_admin_alter_profile_income_and_more'),
        ('dashboard', '0007_delete_recharge_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recharge_Record',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('recharge_payment_id', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharge_user', to='accounts.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
