# Generated by Django 4.2.6 on 2023-12-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_recharge_record_is_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge_record',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
