# Generated by Django 4.2.6 on 2023-12-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_recharge_record_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge_record',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recharge_record',
            name='user_recharge_payment_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
