# Generated by Django 4.2.6 on 2023-12-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_withdraw_record_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
