# Generated by Django 4.2.6 on 2023-12-25 12:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_is_agent'),
        ('dashboard', '0010_withdraw_record_transaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('task_name', models.CharField(blank=True, max_length=100, null=True)),
                ('task_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('task_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_user', to='accounts.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
