# Generated by Django 4.2.6 on 2023-12-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_product_product_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_number',
        ),
    ]
