# Generated by Django 4.2.6 on 2023-10-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forgot_password_token',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='forgot_password_token_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
