# Generated by Django 4.2.6 on 2023-10-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_forgot_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vip_level',
            field=models.IntegerField(default=0),
        ),
    ]
