# Generated by Django 4.2.6 on 2023-10-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_vip_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='income',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='recharge_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
    ]
