# Generated by Django 4.2.6 on 2023-10-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_is_admin_alter_profile_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='recharge_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
