# Generated by Django 4.2.6 on 2023-12-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_is_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='income_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
